/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Client.java
 *
 * Created on Oct 23, 2011, 5:14:24 PM
 */
package searchengine.UserInterface;

import java.io.IOException;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 
 */
public class Client extends javax.swing.JDialog {

    /** Creates new form Client */
    String key1,key2,result1[],result2[],indexMode,setOperation;
    ClientConnecction client;
    public Client(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextField1.setText("Enter KeyWord");

        jTextField2.setText("Enter KeyWord");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "list", "hash", "avl" }));

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "OR", "AND", "Difference" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        client=new ClientConnecction();
    key1=jTextField1.getText();
    key2=jTextField2.getText();
    indexMode=(String) jComboBox1.getSelectedItem();
    setOperation=(String) jComboBox2.getSelectedItem();
   // System.out.println(" Key1"+key1+" key2"+!key2.equalsIgnoreCase("Enter Keyword"));
//    System.out.println("DIC IS "+indexMode+" SET IS "+setOperation);
       /* try {
            System.out.println("hello");
            result1=client.connection(key1,key2,indexMode);
              System.out.println("hello");
                for(int j=0;j<result1.length;j++){
                                  if(result1[j].equals(result1[j]))
                                          jTextArea1.append(result1[j]+"\n");}
        } catch (UnknownHostException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    try{
    if(key1.equalsIgnoreCase("Enter Keyword") && key2.equalsIgnoreCase("Enter Keyword"))
    {
    	jTextArea1.append("Enter KeyWord");
    }
    else if(key1!=null && key2.equalsIgnoreCase("Enter Keyword"))
    {
           
                String w="";
               result1=client.connection(key1,w,indexMode);
  
               if(result1.length==0)
               {
                   jTextArea1.append("Sorry!Search Word is not found.");
               }
               else
               {
                          for(int j=0;j<result1.length;j++)
                          {
                                  if(result1[j].equals(result1[j]))
                                          jTextArea1.append(result1[j]+"\n");
                          }
               }
    }
    else if(key2!=null && key1.equalsIgnoreCase("Enter Keyword"))
    {
    	String w="";
        result1=client.connection(w,key2,indexMode);

        if(result1.length==0)
        {
            jTextArea1.append("Sorry!Search Word is not found.");
        }
        else
        {
                   for(int j=0;j<result1.length;j++)
                   {
                           if(result1[j].equals(result1[j]))
                                   jTextArea1.append(result1[j]+"\n");
                   }
        }
    }
    else if(!key1.equalsIgnoreCase("Enter Keyword") && !key2.equalsIgnoreCase("Enter Keyword"))
    {
    	String w="";
    	if(setOperation.equalsIgnoreCase("OR"))
    	{
    		result1=client.connection(w,key2,indexMode);
    		result2=client.connection(key1,w,indexMode);
    		
    		for(int i=0;i<result1.length;i++)
    		{
    			jTextArea1.append(result1[i]+"\n");
    		}
    		for(int j=0;j<result2.length;j++)
			{
    			jTextArea1.append(result2[j]+"\n");
			}
    	}
    	else if(setOperation.equalsIgnoreCase("AND"))
    	{
    		result1=client.connection(w,key2,indexMode);
    		result2=client.connection(key1,w,indexMode);
    		for(int i=0;i<result1.length;i++)
    		{

    			for(int j=0;j<result2.length;j++)
    			{
    				if(result1[i].equalsIgnoreCase((result2[j])))
    					jTextArea1.append(result1[i]+"\n");
    			}
    		}
    	}
    	else if(setOperation.equalsIgnoreCase("Difference"))
    	{

    		result1=client.connection(w,key2,indexMode);
    		result2=client.connection(key1,w,indexMode);
    		for(int i=0;i<result1.length;i++)
    		{

    			for(int j=0;j<result2.length;j++)
    			{
    				if(result1[i].equalsIgnoreCase((result2[j])))
    				{
    					
    				}
    				else
    				{
    					jTextArea1.append(result1[i]+"\n"+result2[j]+"\n");
    				}
    			}
    		}
    	}
    }
    }
    catch(Exception e){}

}//GEN-LAST:event_jButton1ActionPerformed

private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                Client dialog = new Client(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
